# Travis-CI jobs timeout if they take more than 120 min or if there is
# no output for 10mins. So be careful with what you add here.

language: python
python:
  - "2.6"

script:
  - ./tests/loadAndTest.sh 

