# Travis-CI jobs timeout if they take more than 120 min or if there is
# no output for 10mins. So be careful with what you add here.

language: python
python:
  - "2.6"
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  -psql -c 'create database travis_ci_test;' -U postgres
  - (make)

script:
  - ./test/loadAndTest.sh 

